# Russian translations for Django package.
# Copyright (C) Django Software Foundation and contributors
# This file is distributed under the same license as the Django package.
# Automatically generated, 2018.
# paranoid <brain2dump@gmail.com>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version: Django 2.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-05-17 17:18+0300\n"
"PO-Revision-Date: 2018-05-10 15:52+0300\n"
"Last-Translator: paranoid <brain2dump@gmail.com>\n"
"Language-Team: русский <>\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Generator: Gtranslator 2.91.7\n"

#: ../../releases/2.0.5.txt:3
msgid "Django 2.0.5 release notes"
msgstr "О релизе Django 2.0.5"

#: ../../releases/2.0.5.txt:5
msgid "*May 1, 2018*"
msgstr "*1 мая 2018*"

#: ../../releases/2.0.5.txt:7
msgid "Django 2.0.5 fixes several bugs in 2.0.4."
msgstr "В Django 2.0.5 исправлены некоторые ошибки 2.0.4"

#: ../../releases/2.0.5.txt:10
msgid "Bugfixes"
msgstr "Исправления"

#: ../../releases/2.0.5.txt:12
msgid ""
"Corrected the import paths that ``inspectdb`` generates for ``django.contrib."
"postgres`` fields (:ticket:`29307`)."
msgstr ""
"Исправлены пути импорта которые ``inspectdb`` генерирует для полей ``django."
"contrib.postgres`` (:ticket:`29307`)."

#: ../../releases/2.0.5.txt:15
msgid ""
"Fixed a regression in Django 1.11.8 where altering a field with a unique "
"constraint may drop and rebuild more foreign keys than necessary (:ticket:"
"`29193`)."
msgstr ""
"Исправлена регрессия в Django 1.11.8, где изменение поля с уникальным "
"ограничением может удалять и перестраивать больше внешних ключей, чем "
"необходимо (:ticket:`29193`)"

#: ../../releases/2.0.5.txt:19
msgid ""
"Fixed crashes in ``django.contrib.admindocs`` when a view is a callable "
"object, such as ``django.contrib.syndication.views.Feed`` (:ticket:`29296`)."
msgstr ""
"Устранены падения в  ``django.contrib.admindocs`` в случае если "
"представление это вызываемый объект, такой как ``django.contrib.syndication."
"views.Feed`` (:ticket:`29296`)."

#: ../../releases/2.0.5.txt:22
msgid ""
"Fixed a regression in Django 1.11.12 where ``QuerySet.values()`` or "
"``values_list()`` after combining an annotated and unannotated queryset with "
"``union()``, ``difference()``, or ``intersection()`` crashed due to "
"mismatching columns (:ticket:`29286`)."
msgstr ""
"Исправлена регрессия в Django 1.11.12, где ``QuerySet.values()`` или "
"``values_list()`` после объединения аннотированного и неаннотированного "
"запроса с ``union()``, ``difference()``, или ``intersection()`` падал из-за "
"несоответствия столбцов (:ticket:`29286`)."
